openapi: 3.0.3
info:
  title: Advanced DB Project API
  version: 1.0.0
  description: API documentation for the Advanced DB Project
paths:
  /api/accounts/change-password/:
    post:
      operationId: accounts_change_password_create
      tags:
      - accounts
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/accounts/logout/:
    post:
      operationId: accounts_logout_create
      description: View to handle user logout by blacklisting the refresh token.
      tags:
      - accounts
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/accounts/refresh-token/:
    post:
      operationId: accounts_refresh_token_create
      description: View to refresh JWT tokens.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/accounts/token/:
    post:
      operationId: accounts_token_create
      description: View to obtain JWT token pair for user authentication.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/accounts/users/:
    get:
      operationId: accounts_users_list
      parameters:
      - name: page
        required: false
        in: query
        description: یک شماره صفحه‌ در مجموعه نتایج صفحه‌بندی شده.
        schema:
          type: integer
      tags:
      - accounts
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserList'
          description: ''
  /api/accounts/users/{id}/:
    get:
      operationId: accounts_users_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - accounts
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: accounts_users_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: accounts_users_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/accounts/users/admin/:
    post:
      operationId: accounts_users_admin_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/locations/cities/:
    get:
      operationId: locations_cities_list
      parameters:
      - name: page
        required: false
        in: query
        description: یک شماره صفحه‌ در مجموعه نتایج صفحه‌بندی شده.
        schema:
          type: integer
      tags:
      - locations
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCityList'
          description: ''
    post:
      operationId: locations_cities_create
      tags:
      - locations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/City'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/City'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
          description: ''
  /api/locations/cities/{id}/:
    delete:
      operationId: locations_cities_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - locations
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/locations/provinces/:
    get:
      operationId: locations_provinces_list
      parameters:
      - name: page
        required: false
        in: query
        description: یک شماره صفحه‌ در مجموعه نتایج صفحه‌بندی شده.
        schema:
          type: integer
      tags:
      - locations
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProvinceList'
          description: ''
    post:
      operationId: locations_provinces_create
      tags:
      - locations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Province'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Province'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Province'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Province'
          description: ''
  /api/locations/provinces/{id}/:
    delete:
      operationId: locations_provinces_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - locations
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/locations/villages/:
    get:
      operationId: locations_villages_list
      parameters:
      - name: page
        required: false
        in: query
        description: یک شماره صفحه‌ در مجموعه نتایج صفحه‌بندی شده.
        schema:
          type: integer
      tags:
      - locations
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedVillageList'
          description: ''
    post:
      operationId: locations_villages_create
      tags:
      - locations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Village'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Village'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Village'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Village'
          description: ''
  /api/locations/villages/{id}/:
    delete:
      operationId: locations_villages_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - locations
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    City:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        province:
          type: integer
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - name
      - province
      - updated_at
    PaginatedCityList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/City'
    PaginatedProvinceList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Province'
    PaginatedUserList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/User'
    PaginatedVillageList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Village'
    PatchedUser:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          title: نام کاربری
          description: الزامی. 150 کاراکتر یا کمتر. فقط شامل حروف، اعداد، و علامات
            @/./+/-/_
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: آدرس ایمیل
          maxLength: 254
        first_name:
          type: string
          title: نام
          maxLength: 150
        last_name:
          type: string
          title: نام خانوادگی
          maxLength: 150
        phone:
          type: string
          nullable: true
          maxLength: 15
        password:
          type: string
          writeOnly: true
          title: گذرواژه
          maxLength: 128
        is_active:
          type: boolean
          readOnly: true
          title: فعال
          description: نشان می‌دهد که آیا این کاربر اجازهٔ فعالیت دارد یا خیر. به
            جای حذف کاربر این تیک را بردارید.
        is_staff:
          type: boolean
          title: وضعیت کارمندی
          description: نشان می‌دهد که آیا این کاربر می‌تواند وارد این وبگاه مدیریت
            شود یا خیر.
        is_superuser:
          type: boolean
          title: ابرکاربر
          description: نشان می‌دهد که این کاربر همهٔ اجازه‌ها را دارد بدون آنکه به
            صراحت به او اختصاص داده شده باشد.
        role:
          type: integer
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    Province:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - name
      - updated_at
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          title: نام کاربری
          description: الزامی. 150 کاراکتر یا کمتر. فقط شامل حروف، اعداد، و علامات
            @/./+/-/_
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: آدرس ایمیل
          maxLength: 254
        first_name:
          type: string
          title: نام
          maxLength: 150
        last_name:
          type: string
          title: نام خانوادگی
          maxLength: 150
        phone:
          type: string
          nullable: true
          maxLength: 15
        password:
          type: string
          writeOnly: true
          title: گذرواژه
          maxLength: 128
        is_active:
          type: boolean
          readOnly: true
          title: فعال
          description: نشان می‌دهد که آیا این کاربر اجازهٔ فعالیت دارد یا خیر. به
            جای حذف کاربر این تیک را بردارید.
        is_staff:
          type: boolean
          title: وضعیت کارمندی
          description: نشان می‌دهد که آیا این کاربر می‌تواند وارد این وبگاه مدیریت
            شود یا خیر.
        is_superuser:
          type: boolean
          title: ابرکاربر
          description: نشان می‌دهد که این کاربر همهٔ اجازه‌ها را دارد بدون آنکه به
            صراحت به او اختصاص داده شده باشد.
        role:
          type: integer
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - is_active
      - password
      - updated_at
      - username
    Village:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        city:
          type: integer
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - city
      - created_at
      - id
      - name
      - updated_at
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
